#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=80
start() {
	SEED="$( dd if=/dev/urandom bs=2 count=1 2>&- | hexdump | if read line; then echo 0x${line#* }; fi )"
	SECS="$(( 60 + $SEED % 240 ))" # random time between 1 and 5 minutes
	( sleep $SECS && /usr/sbin/libremap-agent ) &
}

