#!/usr/bin/lua

-- export LUA_PATH="?;?.lua;/usr/lib/lua/?.lua;/root/luasrc/?.lua"

local libremap = require('luci.libremap')
local json = require('luci.json')

local doc = libremap.gather()
print(json.encode(doc))

r = libremap.submit('http://libremap.net/api', 'wurst', doc)
print('response: '..r)
