#!/usr/bin/lua

local uci = require('uci')
local libremap = require('luci.libremap')

local function main()
    local doc = libremap.gather()

    local json = require('luci.json')
    print(json.encode(doc))

    r = libremap.submit('http://libremap.net/api', 'TODO', doc)
    print('response: '..r)
end

main()
