#!/bin/sh

create_conf() {
    cat > /etc/config/libremap <<EOF
config libremap 'settings'
	list api_url 'http://libremap.net/api/'
	list api_url 'http://libremap.berlin.freifunk.net/api'
	option public_url 'http://libremap.net/'
	option fetch_by_name '0'
	option community 'FIXME'
	option community_lat 'FIXME'
	option community_lon 'FIXME'

config plugin 'altermap'
	option enabled '0'

config plugin 'contact'
	option enabled '0'
	option name 'FIXME'
	option email 'FIX@ME'

config plugin 'freifunk'
	option enabled '0'

config plugin 'location'
	option enabled '1'
	option latitude 'FIXME'
	option longitude 'FIXME'
	option elev '0'

config plugin 'olsr'
	option enabled '0'

config plugin 'system'
	option enabled '0'

config plugin 'wireless'
	option enabled '0'

config plugin 'babel'
	option enabled '0'

config plugin 'bmx6'
	option enabled '0'
	
config plugin 'qmp'
	option enabled '0'
EOF
}

# hourly crontab entry with random time
test -f /etc/crontabs/root || touch /etc/crontabs/root
SEED="$( dd if=/dev/urandom bs=2 count=1 2>&- | hexdump | if read line; then echo 0x${line#* }; fi )"
MIN="$(( $SEED % 60 ))"
grep -q "libremap-agent" /etc/crontabs/root || echo "$MIN * * * *        /usr/sbin/libremap-agent" >> /etc/crontabs/root
/etc/init.d/cron restart

# set config only if it is not yet present
if [ ! -f /etc/config/libremap ]; then
	create_conf
fi

# enable plugins if available
PLUGINS="wireless system freifunk olsr location altermap babel bmx6"
for p in $PLUGINS; do 
	if opkg list-installed | grep luci-lib-libremap-$p; then
		uci set libremap.$p=plugin
		uci set libremap.$p.enabled=1
	fi
done
uci commit libremap

